/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package dijkstra-visualization-0.1.0.0 */
#ifndef VERSION_dijkstra_visualization
#define VERSION_dijkstra_visualization "0.1.0.0"
#endif /* VERSION_dijkstra_visualization */
#ifndef MIN_VERSION_dijkstra_visualization
#define MIN_VERSION_dijkstra_visualization(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_dijkstra_visualization */
/* package aeson-2.2.3.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "2.2.3.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_aeson */
/* package base-4.19.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.19.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  19 || \
  (major1) == 4 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package bytestring-0.12.1.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.12.1.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 1)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.6.8 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.8"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 8)
#endif /* MIN_VERSION_containers */
/* package http-types-0.12.4 */
#ifndef VERSION_http_types
#define VERSION_http_types "0.12.4"
#endif /* VERSION_http_types */
#ifndef MIN_VERSION_http_types
#define MIN_VERSION_http_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 4)
#endif /* MIN_VERSION_http_types */
/* package scotty-0.22 */
#ifndef VERSION_scotty
#define VERSION_scotty "0.22"
#endif /* VERSION_scotty */
#ifndef MIN_VERSION_scotty
#define MIN_VERSION_scotty(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  22 || \
  (major1) == 0 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_VERSION_scotty */
/* package text-2.1.1 */
#ifndef VERSION_text
#define VERSION_text "2.1.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_text */
/* package wai-3.2.4 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.4"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 4)
#endif /* MIN_VERSION_wai */
/* package wai-cors-0.2.7 */
#ifndef VERSION_wai_cors
#define VERSION_wai_cors "0.2.7"
#endif /* VERSION_wai_cors */
#ifndef MIN_VERSION_wai_cors
#define MIN_VERSION_wai_cors(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 7)
#endif /* MIN_VERSION_wai_cors */

/* tool gcc-14.0.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.8.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.8.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.8.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.8.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.30.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.30.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  30 || \
  (major1) == 2 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool runghc-9.8.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.8.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "dijkstra-visualization-0.1.0.0-9yvGZH1QnFUK5iRoyBXEnr-server"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
